### ISSUE TITLE
很不错的库

### ISSUE THREAD

**Issue by zhangfisher** [Snowflyt/tinyeffect#1]
很不错，比起Effect这个超级大库，简单多了

可以交流下，https://zhangfisher.github.io/repos/

**Comment by Snowflyt** [comment]
感谢支持。

不过 tinyeffect 与 Effect 虽然在对生成器函数的使用上有些许相似，但实际定位有些差别。Effect 是一个在 TS 中复现 Scala 那边 effect 生态的尝试，更多考虑的其实是如何优雅地处理异步问题，这类库一般会引入所谓“纤程”，也就是“Fiber”，即一种能力更强的轻量级线程。除此之外，这些库也会实现一套相应的标准库，用于适应它们引入的独特编程方式。据我所知，似乎无论是 Effect、Cats Effect 还是 ZIO，都没有在文档中直接提到“Algebraic effects”这个术语。

tinyeffect 的目的则不太相同。tinyeffect 更多是在 Koka 的启发基础上进行设计，只是集中于实现一套相对完备与实用的 Algebraic effect 机制。tinyeffect 本身不会考虑引入一套新的标准库，大概也不会像 Effect 那样直接内置 timeout 和 retry 这样的机制，其内部实现也没有 Fiber 这样的抽象。或许未来会有 @tinyeffect/toolkit 这样的库用于实现标准库或 @tinyeffect/async 这样的库用于实现 timeout/retry 这些机制，但它们不归属于 tinyeffect 本身的开发目的。

以上。

**Comment by zhangfisher** [comment]
提几点建议:

1. 文档显得有些杂乱了，使用vitepress制作一个精美的文档是有必要的，特别是教程
2. 作为刚开源的库，没星没issues时，我习惯不关闭issues，至少让人觉得还有点人气:)
